gpt 862 redis
goxocity/universal-pattern pull request #3
Opened 2021-05-06 15:03 UTC by joscarcab

2021-05-06 16:40 UTC, ajramos requested changes
además de los comentarios acuerdate de tocar el numero de versión del package.json

2021-05-06 16:40 UTC, ajramos commented on index.js
> +        termsOfService: 'http://www.website.com/terms',
ojo con esto please

2021-05-06 16:40 UTC, ajramos commented on index.js
> +          email: 'cesarcasas@bsdsolutions.com.ar',
ojo con esto please

2021-05-07 10:43 UTC, joscarcab commented on index.js
> +        termsOfService: 'http://www.website.com/terms',
listo

2021-05-07 10:43 UTC, joscarcab commented on index.js
> +          email: 'cesarcasas@bsdsolutions.com.ar',
listo

2021-05-07 10:44 UTC, ajramos approved these changes

2021-05-07 10:44 UTC, merged